version: '3.8'

services:
  app:
    build:
      context: ./  # Use the current directory (Lab2) as the build context
      dockerfile: Dockerfile  # Specify the Dockerfile location
    ports:
      - "5000:5000"  # Map container port 5000 to host port 5000
      - "6800:6800"  # Map WebSocket port (6800) to the host
    volumes:
      - ./App/Database:/app/Database  # Mount the Database folder as a volume
    environment:
      - DATABASE_PATH=/app/Database/products.db  # Environment variable for the database path
    command: python app.py  # Run the app.py script when the container starts
